version: '3.8'

services:
  server:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: diploma
      POSTGRES_PASSWORD: diploma
    ports:
      - "5432:5432"
    restart: unless-stopped
